### ISSUE TITLE
new chapter command + echo

### ISSUE THREAD

**Issue by Karkachu** [Jykinturah/ducky-ink#4]
a command where I message ducky like 

"Ducky, I posted a new chapter." and she @ everyone like 

"Hi @ bookbringers! The newest chapter of The Enchanted Kingdom is up! Please remember to keep all spoilers to the appropriate channel, and send any complaints regarding any potential broken hearts to Mono!

Thank you for your support! <3"

- 

and then the echo thingy

**Comment by Jykinturah** [comment]
newChapter command is done, echo is wip.

**Comment by Jykinturah** [comment]
echo is done.
